# Generated by Django 4.2.2 on 2023-06-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_public_id', models.CharField(max_length=255, unique=True, verbose_name='order public id')),
                ('seller_email', models.EmailField(max_length=255, verbose_name='email address')),
                ('buyer_email', models.EmailField(max_length=255, verbose_name='email address')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('image', models.FileField(blank=True, null=True, upload_to='chat_attachments/images/orders/%Y/%m/%d/')),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('escrow_fee', models.DecimalField(decimal_places=2, default=250.0, max_digits=10)),
                ('is_buyer_approved', models.BooleanField(default=False)),
                ('complaints', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=255, unique=True, verbose_name='transaction reference')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrowapp.order')),
            ],
        ),
    ]
