# Generated by Django 4.2.2 on 2023-06-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapp', '0003_order_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction',
            field=models.JSONField(default={}),
        ),
    ]
