# Generated by Django 4.2.2 on 2023-06-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_users_current_subscription_users_subscription_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='current_subscription',
            new_name='current_subscription_transaction',
        ),
    ]
