# Generated by Django 4.2.2 on 2023-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_current_subscription_users_current_subscription_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pics',
            field=models.ImageField(upload_to='images/profile_pics'),
        ),
    ]
