# Generated by Django 4.2.2 on 2023-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_accountno_users_bankname_users_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='paystack_customer_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
