# Generated by Django 4.2.2 on 2023-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_users_paystack_customer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='transaction_pin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='transaction_pin_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
