# Generated by Django 4.2.2 on 2023-06-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_otp_users_otp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
