# Generated by Django 4.2.2 on 2023-06-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_users_otp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='vendor_registration_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
