# Generated by Django 4.2.2 on 2023-06-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_users_is_vendor_users_vendor_registration_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='current_subscription',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='users',
            name='subscription_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
