# Generated by Django 3.2.9 on 2021-12-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableTvProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=100)),
                ('cabletv_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=100)),
                ('isp_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('default_phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('isVerified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('default_phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('auto_data_subscription', models.BooleanField(default=False)),
                ('auto_electricity_subscription', models.BooleanField(default=False)),
                ('auto_cable_subscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredTvSmartCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iuc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('public_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swiftpay_backend.verifiedusers')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredElectricityMeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meternumber', models.CharField(blank=True, max_length=100, null=True)),
                ('public_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swiftpay_backend.verifiedusers')),
            ],
        ),
        migrations.CreateModel(
            name='DataSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_code', models.CharField(max_length=100)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(max_length=100)),
                ('plan_provider_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swiftpay_backend.networkproviders')),
            ],
        ),
        migrations.CreateModel(
            name='CableTvBouquets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_bouquet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_bouquet_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tv_bouquet_provider_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swiftpay_backend.cabletvproviders')),
            ],
        ),
    ]
