# Generated by Django 3.2.9 on 2021-12-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasubscriptions',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
