# Generated by Django 3.2.9 on 2021-12-24 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0002_alter_datasubscriptions_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasubscriptions',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('5782df5e-5f2c-45ba-8a95-5d782c20d14f'), max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('61f23777-5724-45a6-a11e-0096706ebaf1'), max_length=100),
        ),
    ]
