# Generated by Django 3.2.9 on 2021-12-24 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0004_auto_20211223_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('af9e3768-bab3-44c0-8fc8-4e56850b1d2f'), max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('4c266811-2cc0-42bb-8bf5-be2a8ccd00a5'), max_length=100),
        ),
    ]
