# Generated by Django 3.2.9 on 2021-12-24 05:26

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('swiftpay_backend', '0005_auto_20211223_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedusers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='verifiedusers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='verifiedusers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='verifiedusers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='verifiedusers',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='unverifiedusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='unverifiedusers',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='unverifiedusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='unverifiedusers',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifiedusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='default_phonenumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='middlename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('0408cc8c-27e4-437f-a9a4-e79fef412465'), max_length=100),
        ),
        migrations.AlterField(
            model_name='unverifiedusers',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='default_phonenumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('3f666bc6-e9d1-4a69-8965-b09d140d1471'), max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
