# Generated by Django 3.2.9 on 2021-12-24 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0006_auto_20211223_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('b33b46e8-145b-461e-9672-1837e4233884'), max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('09bf84af-cf95-4e92-a293-679a9aa4d079'), max_length=100),
        ),
    ]
