# Generated by Django 3.2.9 on 2021-12-24 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0007_auto_20211223_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('e66df800-4969-40b9-bf58-57ec7e909c4c'), max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('d91a4073-227f-4f0a-bd8b-3d41424b2583'), max_length=100),
        ),
    ]
