# Generated by Django 3.2.9 on 2021-12-25 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0008_auto_20211224_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('4033d560-9d49-43c6-abbf-bd01fda60749'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('9a6fe5ee-c66d-4c5b-8293-5df1e0277031'), max_length=100),
        ),
    ]
