# Generated by Django 3.2.9 on 2021-12-25 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0013_auto_20211225_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('6de18123-75cc-49f0-829a-9eb2a25bf035'), max_length=100),
        ),
    ]
