# Generated by Django 3.2.9 on 2021-12-26 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0014_alter_verifiedusers_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabletvproviders',
            name='cabletv_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cabletvproviders',
            name='public_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='networkproviders',
            name='isp_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='networkproviders',
            name='public_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('c8949b79-67b5-4664-818f-87b82b4cc6b7'), max_length=100),
        ),
    ]
