# Generated by Django 3.2.9 on 2021-12-26 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0015_auto_20211225_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('1d6fc9ba-b47e-42fa-8931-cc4b18b3bff5'), max_length=100),
        ),
    ]
