# Generated by Django 3.2.9 on 2021-12-26 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0016_alter_verifiedusers_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabletvbouquets',
            name='tv_bouquet_variation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('c1884702-983a-44f6-a90d-8e15d9dbfb4d'), max_length=100),
        ),
    ]
