# Generated by Django 3.2.9 on 2021-12-27 06:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0019_auto_20211226_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncart',
            name='amount',
            field=models.DecimalField(decimal_places=2,  max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactioncart',
            name='buyer_public_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('33c1de4d-8489-4eea-b3a7-943e38cc21e9'), max_length=100),
        ),
    ]
