# Generated by Django 3.2.9 on 2021-12-27 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0020_auto_20211226_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('db2d4caf-9a65-4ef9-a652-d6fc972f87e3'), max_length=100),
        ),
    ]
