# Generated by Django 3.2.9 on 2021-12-27 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0022_auto_20211226_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncart',
            old_name='amounts',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('c79b0578-0323-4f67-8a5f-a78a9374eadb'), max_length=100),
        ),
    ]
