# Generated by Django 3.2.9 on 2021-12-27 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0023_auto_20211226_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('245b683e-7e2c-48aa-8bd8-fbaa47bb1a44'), max_length=100),
        ),
    ]
