# Generated by Django 3.2.9 on 2021-12-27 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0024_alter_verifiedusers_public_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionCart',
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('ff634fc6-2fa7-4149-960b-94038d8a1ecf'), max_length=100),
        ),
    ]
