# Generated by Django 3.2.9 on 2021-12-27 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0026_auto_20211226_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('3cf67240-b2e8-43ea-843b-4b8fdca76afd'), max_length=100),
        ),
    ]
