# Generated by Django 3.2.9 on 2021-12-27 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0028_auto_20211226_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('b8ffa66a-6e1f-4a88-aae1-09b67fb751a5'), max_length=100),
        ),
    ]
