# Generated by Django 3.2.9 on 2021-12-27 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0029_alter_verifiedusers_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtimepurchasehistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cablesubscriptionhistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='datasubscriptionhistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='electricitypurchasehistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transactioncart',
            name='amount',
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('0a02eb5d-08f5-477d-ac24-33c75a00ad86'), max_length=100),
        ),
    ]
