# Generated by Django 3.2.9 on 2021-12-27 06:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0030_auto_20211226_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioncart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactioncart',
            name='buyer_public_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('42bf4815-e36b-4f95-b5a2-f8b6758319bc'), max_length=100),
        ),
    ]
