# Generated by Django 3.2.9 on 2021-12-27 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0033_auto_20211226_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirtimePurchaseHistory',
        ),
        migrations.DeleteModel(
            name='CableSubscriptionHistory',
        ),
        migrations.DeleteModel(
            name='DataSubscriptionHistory',
        ),
        migrations.DeleteModel(
            name='ElectricityPurchaseHistory',
        ),
        migrations.DeleteModel(
            name='TransactionCart',
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('fa1e5663-eda4-491b-ad4d-2e09efbc0591'), max_length=100),
        ),
    ]
