# Generated by Django 3.2.9 on 2021-12-27 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0035_auto_20211226_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('13123e7d-edf4-433f-a8e9-71629497b7b2'), max_length=100),
        ),
    ]
