# Generated by Django 3.2.9 on 2021-12-27 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0036_alter_verifiedusers_public_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricityPurchaseHistory',
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('2760394e-0ed7-442e-96c8-803a2d89fab0'), max_length=100),
        ),
    ]
