# Generated by Django 3.2.9 on 2021-12-27 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0037_auto_20211227_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('05833f67-d3dc-4071-8669-c53ee845eaeb'), max_length=100),
        ),
    ]
