# Generated by Django 3.2.9 on 2021-12-27 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0039_alter_verifiedusers_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_public_id', models.CharField(max_length=100, unique=True)),
                ('disco', models.CharField(max_length=100, unique=True)),
                ('meter_number', models.IntegerField(unique=True)),
                ('meter_type', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('1cdf0f8d-d608-4779-b60a-25f6f80c0442'), max_length=100),
        ),
    ]
