# Generated by Django 3.2.9 on 2021-12-27 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0040_auto_20211227_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('a5e61995-30f7-411a-a294-5158603241d3'), max_length=100),
        ),
    ]
