# Generated by Django 3.2.9 on 2021-12-27 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0041_alter_verifiedusers_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncart',
            name='buyer_public_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('eacecc05-c5b5-446c-aed1-6c8d946acdf5'), max_length=100),
        ),
    ]
