# Generated by Django 3.2.9 on 2021-12-27 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0042_auto_20211227_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncart',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedusers',
            name='public_id',
            field=models.CharField(default=uuid.UUID('de331123-35ba-4fe7-924b-82a1c62da2f2'), max_length=100),
        ),
    ]
