# Generated by Django 3.2.9 on 2021-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0044_auto_20211227_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityDiscos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=100, unique=True)),
                ('disco_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
