# Generated by Django 3.2.9 on 2021-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0046_electricitydiscos_disco_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitydiscos',
            name='disco_code',
            field=models.CharField(max_length=100),
        ),
    ]
