# Generated by Django 3.2.9 on 2021-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0048_transactioncart_cart_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='cart_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='date_time',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100),
        ),
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='order_id',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='vend_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='cart_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='date_time',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100),
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='order_id',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='vend_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='cart_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='date_time',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100),
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='order_id',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='vend_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='cart_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='date_time',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='order_id',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='vend_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactioncart',
            name='date_time',
            field=models.CharField(default='2021-12-29--12:48 am', max_length=100),
        ),
        migrations.AddField(
            model_name='transactioncart',
            name='vend_status',
            field=models.BooleanField(default=False),
        ),
    ]
