# Generated by Django 3.2.9 on 2022-01-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0049_auto_20211231_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
