# Generated by Django 3.2.9 on 2022-01-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0050_auto_20220101_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='buyer_public_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='network_provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='bouquet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='buyer_public_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='cable_provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='buyer_public_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='network_provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='plan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='variation_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='buyer_public_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='disco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='meter_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
