# Generated by Django 3.2.9 on 2022-01-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0052_airtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='network_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
