# Generated by Django 3.2.9 on 2022-01-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0053_airtime_network_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtime',
            name='amount',
        ),
    ]
