# Generated by Django 3.2.9 on 2022-01-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0054_remove_airtime_amount'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='airtime',
    #         # name='network_id',
    #     ),
    # ]
    
