# Generated by Django 3.2.9 on 2022-01-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0055_remove_airtime_network_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasubscriptions',
            old_name='plan_provider_id',
            new_name='plan_provider',
        ),
        migrations.AlterField(
            model_name='datasubscriptions',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
