# Generated by Django 3.2.9 on 2022-01-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0057_rename_tv_bouquet_provider_id_cabletvbouquets_tv_bouquet_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitydiscos',
            name='api_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='electricitydiscos',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electricitydiscos',
            name='disco_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electricitydiscos',
            name='disco_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electricitydiscos',
            name='public_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
