# Generated by Django 3.2.9 on 2022-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0058_auto_20220102_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitydiscos',
            name='discount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
