# Generated by Django 3.2.9 on 2022-01-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0059_alter_electricitydiscos_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='iuc_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
