# Generated by Django 3.2.9 on 2022-01-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0060_alter_cablesubscriptionhistory_iuc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='meter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
