# Generated by Django 3.2.9 on 2022-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0061_alter_electricitypurchasehistory_meter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
