# Generated by Django 3.2.9 on 2022-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0062_auto_20220104_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='amount_charged',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
