# Generated by Django 3.2.9 on 2022-01-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0063_electricitypurchasehistory_amount_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='amount_charged',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
