# Generated by Django 3.2.9 on 2022-01-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0066_auto_20220107_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncart',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
