# Generated by Django 3.2.9 on 2022-01-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0067_auto_20220107_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncart',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactioncart',
            name='date_time',
            field=models.CharField(max_length=100),
        ),
    ]
