# Generated by Django 3.2.9 on 2022-01-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0068_auto_20220107_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimepurchasehistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cablesubscriptionhistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datasubscriptionhistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='electricitypurchasehistory',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
