# Generated by Django 3.2.9 on 2022-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0069_auto_20220107_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactioncart',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
