# Generated by Django 3.2.9 on 2022-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0070_auto_20220109_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
