# Generated by Django 3.2.9 on 2022-01-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0071_auto_20220109_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
