# Generated by Django 3.2.9 on 2022-01-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0072_auto_20220109_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabletvbouquets',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabletvproviders',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasubscriptions',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricitydiscos',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactioncart',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
