# Generated by Django 3.2.9 on 2022-01-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0073_auto_20220110_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimepurchasehistory',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cablesubscriptionhistory',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasubscriptionhistory',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricitypurchasehistory',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
