# Generated by Django 3.2.9 on 2022-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0074_auto_20220110_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkproviders',
            name='api_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
