# Generated by Django 3.2.9 on 2022-03-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0075_networkproviders_api_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
