# Generated by Django 3.2.9 on 2022-03-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0077_remove_airtime_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimePeriodicSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_public_id', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('subscription_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_label', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recurrence', models.CharField(blank=True, max_length=100, null=True)),
                ('last_subscription', models.FloatField(blank=True, null=True)),
                ('next_subscription', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('api_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CablePeriodicSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_public_id', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('subscription_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_label', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recurrence', models.CharField(blank=True, max_length=100, null=True)),
                ('last_subscription', models.FloatField(blank=True, null=True)),
                ('next_subscription', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('api_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataPeriodicSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_public_id', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('subscription_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_label', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recurrence', models.CharField(blank=True, max_length=100, null=True)),
                ('last_subscription', models.FloatField(blank=True, null=True)),
                ('next_subscription', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('api_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityPeriodicSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_public_id', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100, unique=True)),
                ('subscription_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_label', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_recurrence', models.CharField(blank=True, max_length=100, null=True)),
                ('last_subscription', models.FloatField(blank=True, null=True)),
                ('next_subscription', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('api_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
