# Generated by Django 3.2.9 on 2022-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0078_airtimeperiodicsubscriptions_cableperiodicsubscriptions_dataperiodicsubscriptions_electricityperiodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='service_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
