# Generated by Django 3.2.9 on 2022-04-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0079_airtimeperiodicsubscriptions_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_label',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
