# Generated by Django 3.2.9 on 2022-04-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0080_alter_airtimeperiodicsubscriptions_subscription_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataperiodicsubscriptions',
            name='service_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataperiodicsubscriptions',
            name='subscription_label',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
