# Generated by Django 3.2.9 on 2022-04-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0081_auto_20220401_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataperiodicsubscriptions',
            name='unitprice',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
