# Generated by Django 3.2.9 on 2022-04-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0082_dataperiodicsubscriptions_unitprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableperiodicsubscriptions',
            name='service_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cableperiodicsubscriptions',
            name='unitprice',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
