# Generated by Django 3.2.9 on 2022-04-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0084_auto_20220402_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='periodicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='timestamp_created',
            field=models.FloatField(blank=True, default=1648938686.048458, null=True),
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='timestamp_lastedit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cableperiodicsubscriptions',
            name='periodicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cableperiodicsubscriptions',
            name='timestamp_created',
            field=models.FloatField(blank=True, default=1648938686.048458, null=True),
        ),
        migrations.AddField(
            model_name='cableperiodicsubscriptions',
            name='timestamp_lastedit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataperiodicsubscriptions',
            name='periodicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataperiodicsubscriptions',
            name='timestamp_created',
            field=models.FloatField(blank=True, default=1648938686.048458, null=True),
        ),
        migrations.AddField(
            model_name='dataperiodicsubscriptions',
            name='timestamp_lastedit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityperiodicsubscriptions',
            name='periodicity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricityperiodicsubscriptions',
            name='timestamp_created',
            field=models.FloatField(blank=True, default=1648938686.048458, null=True),
        ),
        migrations.AddField(
            model_name='electricityperiodicsubscriptions',
            name='timestamp_lastedit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
