# Generated by Django 3.2.9 on 2022-04-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0086_auto_20220402_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableperiodicsubscriptions',
            name='timestamp_created',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataperiodicsubscriptions',
            name='timestamp_created',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricityperiodicsubscriptions',
            name='timestamp_created',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
