# Generated by Django 3.2.9 on 2022-04-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0087_auto_20220402_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly', models.BooleanField(default=False)),
                ('bi_monthly', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
            ],
        ),
    ]
