# Generated by Django 3.2.9 on 2022-04-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0088_batchprocstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batchprocstatus',
            name='bi_monthly',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='batchprocstatus',
            name='monthly',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='batchprocstatus',
            name='weekly',
            field=models.BooleanField(null=True),
        ),
    ]
