# Generated by Django 3.2.9 on 2022-04-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0089_auto_20220408_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableperiodicsubscriptions',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataperiodicsubscriptions',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricityperiodicsubscriptions',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
