# Generated by Django 3.2.9 on 2022-04-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0091_dataperiodicsubscriptions_subscription_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataperiodicsubscriptions',
            old_name='subscription_code',
            new_name='service_code',
        ),
        migrations.AddField(
            model_name='cableperiodicsubscriptions',
            name='service_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricityperiodicsubscriptions',
            name='service_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
