# Generated by Django 3.2.9 on 2022-11-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0092_auto_20220410_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
