# Generated by Django 3.2.9 on 2023-02-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftpay_backend', '0093_apiproviders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirtimePeriodicSubscriptions',
        ),
        migrations.DeleteModel(
            name='CablePeriodicSubscriptions',
        ),
        migrations.DeleteModel(
            name='DataPeriodicSubscriptions',
        ),
        migrations.DeleteModel(
            name='ElectricityPeriodicSubscriptions',
        ),
    ]
