# Generated by Django 4.2.2 on 2023-07-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_cabletvbouquets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabletvbouquets',
            old_name='tv_bouquet_name',
            new_name='bouquet_code',
        ),
        migrations.RenameField(
            model_name='cabletvbouquets',
            old_name='tv_bouquet_variation_id',
            new_name='bouquet_name',
        ),
        migrations.RenameField(
            model_name='cabletvbouquets',
            old_name='tv_bouquet_price',
            new_name='bouquet_price',
        ),
        migrations.RenameField(
            model_name='cabletvbouquets',
            old_name='tv_bouquet_provider',
            new_name='bouquet_provider',
        ),
    ]
