# Generated by Django 4.2.2 on 2023-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(default='Debit Card', max_length=255, verbose_name='Payment Channel'),
        ),
    ]
