# Generated by Django 4.2.2 on 2023-06-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapp', '0005_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPaymentpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_public_id', models.CharField(max_length=255, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_account_no', models.CharField(max_length=255)),
                ('vendor_email', models.CharField(max_length=255)),
            ],
        ),
    ]
