# Generated by Django 4.2.2 on 2023-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapp', '0006_vendorpaymentpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpaymentpool',
            name='bankname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorpaymentpool',
            name='settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpaymentpool',
            name='vendor_paystack_customer_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
