# Generated by Django 3.2.9 on 2023-02-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosubscriptions', '0002_auto_20230210_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='paystack_customer_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
