# Generated by Django 3.2.9 on 2023-02-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosubscriptions', '0003_auto_20230210_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='api_provider',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_label',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_recipient',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_recurrence',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='subscription_volume',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='timestamp_created',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='timestamp_lastedit',
        ),
        migrations.RemoveField(
            model_name='airtimeperiodicsubscriptions',
            name='user_public_id',
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='created_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autosubscriptions.customers'),
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autosubscriptions.plans'),
        ),
        migrations.AddField(
            model_name='airtimeperiodicsubscriptions',
            name='updated_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='owner',
            field=models.CharField(blank=True, default='ekoemmanueljavl@gmail.com', max_length=100, null=True),
        ),
    ]
