# Generated by Django 3.2.9 on 2023-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosubscriptions', '0004_auto_20230210_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
