# Generated by Django 3.2.9 on 2023-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosubscriptions', '0006_auto_20230212_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='iuc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='meter_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
