# Generated by Django 4.2.2 on 2023-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_airtimedatatransactionhistory_pendingpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayments',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
