# Generated by Django 4.2.2 on 2023-07-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_pendingpayments_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayments',
            name='order_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
