# Generated by Django 4.2.2 on 2023-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_pendingpayments_order_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableTvProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=100, unique=True)),
                ('cabletv_name', models.CharField(max_length=100, unique=True)),
                ('api_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
