# Generated by Django 4.2.2 on 2023-07-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_cabletvproviders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableTvBouquets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_bouquet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_bouquet_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tv_bouquet_variation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_bouquet_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.cabletvproviders')),
            ],
        ),
    ]
